name: Tests

on:
  push:
    branches: 
      - develop
      - master

jobs:
  gui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Unit test + integration tests
        run: mvn verify
      - name: Build with Maven
        run: mvn -B package
      - run: mkdir artifacts && cp api/target/*.jar artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: library
          path: artifacts
